name: Build Debug APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  ANDROID_SDK_ROOT: /usr/local/android-sdk

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip tar

      - name: Make SDK installer executable
        run: |
          chmod +x android/scripts/install-android-sdk.sh

      - name: Install Android SDK (script)
        run: |
          ./android/scripts/install-android-sdk.sh
        env:
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}

      - name: Add platform-tools to PATH
        run: echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH

      - name: Install Gradle 7.4.2
        run: |
          wget -q https://services.gradle.org/distributions/gradle-7.4.2-bin.zip -O gradle.zip
          sudo unzip -q gradle.zip -d /opt/gradle
          rm gradle.zip
          echo "/opt/gradle/gradle-7.4.2/bin" >> $GITHUB_PATH

      - name: Build debug APK
        working-directory: android
        run: |
          # используем системный gradle (установленный выше). Если у вас есть gradlew - можно заменить на ./gradlew
          gradle :app:assembleDebug --no-daemon

      - name: Upload debug APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android/app/build/outputs/apk/debug/*.apk